version: "3.8"
services:
  web:
    #    platform: linux/x86_64 # for mac m1
    image: "docker.io/moodlehq/moodle-php-apache:5.6"
    container_name: moodle_web
    volumes:
      - "./html:/var/www/html"
      - "./moodledata:/var/www/moodledata"
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    #    platform: linux/x86_64 # for mac m1
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "mysql_user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    command: mysqld --sql_mode=""
    ports:
      - "3309:3306"
    expose:
      - "3306"
    volumes:
      - moodle_learn-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      retries: 3
      timeout: 5s
# Names our volume
volumes:
  moodle_learn-db:
